GET http://localhost:3003/api/blogs



#####
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2V1c2VybmFtZTMzIiwiaWQiOiI2MjJkNDU2OWUzMDI0MGI0MzNjNmYwNDkiLCJpYXQiOjE2NDcxMzQxMTYsImV4cCI6MTY0NzEzNzcxNn0.X4CqaVK15PO0AQQOyp8PZfCfE4UUqXB-MAjAt_l2JDc

{
    "title": "teeeeet2333",
    "author": "teeeeeeeee22e333t",
    "url": "teee33ee22t",
    "likes": 500
}



###
DELETE http://localhost:3003/api/blogs/622d4aca5911a6f4e4a1bcdf
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2V1c2VybmFtZTMzMyIsImlkIjoiNjIyZDRhZWU1OTExYTZmNGU0YTFiY2U0IiwiaWF0IjoxNjQ3MTM1NDcyLCJleHAiOjE2NDcxMzkwNzJ9.0KuwdPYpaLBUBnxGxiSrJ0yoiK4BN7tx8Pq-Dc5RjQs


{
"title": "teeeeet2333",
"author": "teeeeeeeee22e333t",
"url": "teee33ee22t",
"likes": 500,
"user": "622d4569e30240b433c6f049",
"id": "622d4aca5911a6f4e4a1bcdf"
}







# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "",
#     "number": "911-911-9112"
# }

# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "I am fake name2",
#     "number": ""
# }


# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "Mary Poppendieck",
#     "number": "911-911-911"
# }

# #####
# DELETE http://localhost:3001/api/persons/3
