GET http://localhost:3003/api/users



#####
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "fakeusername33",
    "name": "fakename33",
    "password": "fakepassword33"
}








# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "",
#     "number": "911-911-9112"
# }

# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "I am fake name2",
#     "number": ""
# }


# #####
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "Mary Poppendieck",
#     "number": "911-911-911"
# }

# #####
# DELETE http://localhost:3001/api/persons/3
